#!/bin/bash

FOAMMODULE=OpenFOAM/8-foss-2020a

#PBS -o pbs_out.dat
#PBS -e pbs_err.dat
#PBS -N Job-Name
#PBS -l nodes=1:ppn=4

cd $PBS_O_WORKDIR
module purge
module add $FOAMMODULE
source $FOAM_BASH

#-------------------------------------------------------#

mpirun -np 4 simpleFoam -parallel
reconstructPar

rm -rf processor*
